version: 2.0

jobs:

  lint:
    docker:
      - image: continuumio/miniconda3
    steps:
      - run: pip install flake8
      - checkout
      - run: flake8

  tests:
    docker:
      - image: continuumio/miniconda3
    steps:
      - run: conda install pytorch-cpu numpy -c pytorch
      - run: pip install pytest-cov codecov
      - checkout
      - run: python setup.py install
      - run: py.test --cov py_config_runner --cov-report term-missing -vvv
      - run: codecov
      - save_cache:
          key: conda-py37
          paths:
            - /opt/conda

  deploy:
    docker:
      - image: continuumio/miniconda3
    steps:
      - restore_cache:
          key: conda-py37
      - checkout
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run:
          command: |
            echo -e "[pypi]" > ~/.pypirc
            echo -e "username = @token" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run: twine upload dist/*


workflows:
  version: 2
  config_runner_ci:
    jobs:
      - lint:
          filters:
            tags:
              only: /v.*/
      - tests:
          requires:
            - lint
          filters:
            tags:
              only: /v.*/
      - deploy:
          requires:
            - tests
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/

